# 我们有内置的标识符默认值,但如果您手动指定标识符,
# 我们将不使用默认值。因此请确保您已经**定义了完整的标识符**。
[identifiers]
# 有两种类型的标识符:
# 一种是 "symbol",它会根据符号表自动查找目标函数;
# 另一种是 "rva",它直接指定函数的RVA。
# 下面,我提供了它们各自的语法。

# 标识符的类型是一个数组，我们会按照数组中的顺序匹配函数。

#V8_SCRIPT_COMPILER_COMPILE_FUNCTION_INTERNAL = [{ type = "symbol", symbols = [
#    """_ZN2v814ScriptCompiler23CompileFunctionInternalENS_5LocalINS_\
#    7ContextEEEPNS0_6SourceEmPNS1_INS_6StringEEEmPNS1_INS_6ObjectEEE\
#    NS0_14CompileOptionsENS0_13NoCacheReasonEPNS1_INS_14ScriptOrModu\
#    leEEE""",
#    """?CompileFunctionInternal@ScriptCompiler@v8@@CA?AV?$MaybeLocal\
#    @VFunction@v8@@@2@V?$Local@VContext@v8@@@2@PEAVSource@12@_KQEAV?\
#    $Local@VString@v8@@@2@2QEAV?$Local@VObject@v8@@@2@W4CompileOptio\
#    ns@12@W4NoCacheReason@12@PEAV?$Local@VScriptOrModule@v8@@@2@@Z"""] }]
V8_SCRIPT_COMPILER_COMPILE_FUNCTION_INTERNAL = [{ type = "rva", module_name = "node", rva = 0x00a3ffb0 }]
V8_STRING_UTF8LENGTH = [{ type = "symbol", symbols = [
    """_ZNK2v86String10Utf8LengthEPNS_7IsolateE""",
    """?Utf8Length@String@v8@@QEBAHPEAVIsolate@2@@Z"""] }]
V8_STRING_WRITE_UTF8 = [{ type = "symbol", symbols = [
    """_ZNK2v86String9WriteUtf8EPNS_7IsolateEPciPii""",
    """?WriteUtf8@String@v8@@QEBAHPEAVIsolate@2@PEADHPEAHH@Z"""] }]
V8_CONTEXT_GET_ISOLATE = [{ type = "symbol", symbols = [
    """_ZN2v87Context10GetIsolateEv""",
    """?GetIsolate@Context@v8@@QEAAPEAVIsolate@2@XZ"""] }]
V8_STRING_NEW_FROM_UTF8 = [{ type = "symbol", symbols = [
    """_ZN2v86String11NewFromUtf8EPNS_7IsolateEPKcNS_13NewStringTypeEi""",
    """?NewFromUtf8@String@v8@@SA?AV?$MaybeLocal@VString@v8@@@2@PEAV\
    Isolate@2@PEBDW4NewStringType@2@H@Z"""] }]


[rules.hook_console_log]
matcher = { type = "resource-name-keyword", keyword = "hello_world.js" }

processors = [
    { type = "insert-before", content = """\
    const originalConsoleLog = console.log
    console.log = function () {
      originalConsoleLog('now you see :)')
      return originalConsoleLog.apply(this, arguments)
    }""" },
    { type = "insert-after", content = """\
    console.log = originalConsoleLog
    """ }
]
